function ConvertTo-PCXEditedTimelineMarker {

    <#
    .SYNOPSIS
        Projects Premiere markers onto the edited timeline.

    .DESCRIPTION
        Transforms PCXLab.PremiereMarker objects from original source timeline
        coordinates to edited video timeline coordinates using a PCXLab.TimelineMap.

        Markers that fall entirely within removed segments are discarded.
        Markers that fall within kept segments are shifted to their corresponding
        edited timeline positions. Markers that partially overlap kept segments
        are clamped to the visible kept interval boundaries.

    .PARAMETER Marker
        One or more PCXLab.PremiereMarker objects to project.

    .PARAMETER TimelineMap
        A PCXLab.TimelineMap object describing the kept intervals.

    .OUTPUTS
        PCXLab.PremiereMarker
    #>

    [CmdletBinding()]
    [OutputType([PSCustomObject])]
    param(

        [Parameter(Mandatory, ValueFromPipeline)]
        [ValidateNotNull()]
        [object[]]$Marker,

        [Parameter(Mandatory)]
        [ValidateNotNull()]
        [object]$TimelineMap

    )

    begin {
        if ($TimelineMap.PSTypeNames -notcontains 'PCXLab.TimelineMap') {
            throw 'TimelineMap must be a PCXLab.TimelineMap object.'
        }
        $markers = [System.Collections.Generic.List[object]]::new()
    }

    process {
        foreach ($m in $Marker) {
            if ($m.PSTypeNames -notcontains 'PCXLab.PremiereMarker') {
                throw 'Marker must be a PCXLab.PremiereMarker object.'
            }
            $markers.Add($m)
        }
    }

    end {
        $invariantCulture = [System.Globalization.CultureInfo]::InvariantCulture

        foreach ($m in $markers) {

            $mStart = [double]$m.StartSeconds
            $mEnd   = [double]$m.EndSeconds
            $isPoint = ($mStart -eq $mEnd)

            foreach ($interval in $TimelineMap.Intervals) {

                $iStart = [double]$interval.OriginalStartSeconds
                $iEnd   = [double]$interval.OriginalEndSeconds
                $eStart = [double]$interval.EditedStartSeconds

                if ($isPoint) {

                    if ($mStart -ge $iStart -and $mStart -le $iEnd) {

                        $pStart = [Math]::Round(($eStart + ($mStart - $iStart)), 3)

                        $startTs     = [TimeSpan]::FromSeconds($pStart).ToString('hh\:mm\:ss\.fff')
                        $endTs       = $startTs
                        $durationFmt = '0 sec'

                        $commentLines = [System.Collections.Generic.List[string]]::new()
                        $commentLines.Add("Type           : $($m.MarkerKind)")
                        if (-not [string]::IsNullOrWhiteSpace($m.MarkerSubKind)) {
                            $commentLines.Add("SubType        : $($m.MarkerSubKind)")
                        }
                        $commentLines.Add('')
                        $commentLines.Add("Start          : $startTs")
                        $commentLines.Add("End            : $endTs")
                        $commentLines.Add("Duration       : $durationFmt")
                        $commentLines.Add('')
                        $commentLines.Add('Generated by PCXLab.VideoTools')

                        New-PCXPremiereMarkerObject `
                            -StartSeconds  $pStart `
                            -EndSeconds    $pStart `
                            -Name          $m.Name `
                            -Comments      ($commentLines -join "`n") `
                            -MarkerType    $m.MarkerType `
                            -MarkerKind    $m.MarkerKind `
                            -MarkerSubKind $m.MarkerSubKind `
                            -ColorIndex    $m.ColorIndex

                    }

                }
                else {

                    $overlapStart = [Math]::Max($mStart, $iStart)
                    $overlapEnd   = [Math]::Min($mEnd, $iEnd)

                    if ($overlapStart -lt $overlapEnd) {

                        $pStart = [Math]::Round(($eStart + ($overlapStart - $iStart)), 3)
                        $pEnd   = [Math]::Round(($eStart + ($overlapEnd - $iStart)), 3)
                        $pDur   = [Math]::Round(($pEnd - $pStart), 3)

                        $startTs     = [TimeSpan]::FromSeconds($pStart).ToString('hh\:mm\:ss\.fff')
                        $endTs       = [TimeSpan]::FromSeconds($pEnd).ToString('hh\:mm\:ss\.fff')
                        $durationFmt = $pDur.ToString('0.###', $invariantCulture) + ' sec'

                        $commentLines = [System.Collections.Generic.List[string]]::new()
                        $commentLines.Add("Type           : $($m.MarkerKind)")
                        if (-not [string]::IsNullOrWhiteSpace($m.MarkerSubKind)) {
                            $commentLines.Add("SubType        : $($m.MarkerSubKind)")
                        }
                        $commentLines.Add('')
                        $commentLines.Add("Start          : $startTs")
                        $commentLines.Add("End            : $endTs")
                        $commentLines.Add("Duration       : $durationFmt")
                        $commentLines.Add('')
                        $commentLines.Add('Generated by PCXLab.VideoTools')

                        New-PCXPremiereMarkerObject `
                            -StartSeconds  $pStart `
                            -EndSeconds    $pEnd `
                            -Name          $m.Name `
                            -Comments      ($commentLines -join "`n") `
                            -MarkerType    $m.MarkerType `
                            -MarkerKind    $m.MarkerKind `
                            -MarkerSubKind $m.MarkerSubKind `
                            -ColorIndex    $m.ColorIndex

                    }

                }

            }

        }
    }

}
