function Convert-PCXVideoSegmentToPremiereMarker {

    <#
    .SYNOPSIS
        Converts a PCXLab.VideoSegment into a normalized Premiere marker object.

    .DESCRIPTION
        Transforms an editing video segment into a PCXLab.PremiereMarker.

        The resulting marker is always stamped with:
            MarkerKind    = 'Editing'
            MarkerSubKind = the segment Action (e.g. 'Keep', 'Remove')

        Marker title
        ------------
        The segment Action is used directly as the concise display name
        (e.g. 'Keep', 'Remove').

        Marker comments
        ---------------
        A structured key-value block is generated:

            Type           : Editing
            Decision       : Remove

            Start          : 00:00:03.004
            End            : 00:00:04.430
            Duration       : 1.426 sec

            Generated by PCXLab.VideoTools

    .PARAMETER Segment
        The PCXLab.VideoSegment object to convert.

    .OUTPUTS
        PCXLab.PremiereMarker
    #>

    [CmdletBinding()]
    [OutputType([PSCustomObject])]
    param(

        [Parameter(Mandatory)]
        [ValidateNotNull()]
        [object]$Segment

    )

    if ($Segment.PSTypeNames -notcontains 'PCXLab.VideoSegment') {
        throw 'InputObject must be a PCXLab.VideoSegment object.'
    }

    $invariantCulture = [System.Globalization.CultureInfo]::InvariantCulture

    $startSeconds = if ($null -ne $Segment.StartSeconds) {
        [double]$Segment.StartSeconds
    }
    elseif ($Segment.Start -is [TimeSpan]) {
        $Segment.Start.TotalSeconds
    }
    else {
        0.0
    }

    $endSeconds = if ($null -ne $Segment.EndSeconds) {
        [double]$Segment.EndSeconds
    }
    elseif ($Segment.End -is [TimeSpan]) {
        $Segment.End.TotalSeconds
    }
    else {
        $startSeconds
    }

    $durationSeconds = if ($null -ne $Segment.DurationSeconds) {
        [double]$Segment.DurationSeconds
    }
    elseif ($Segment.Duration -is [TimeSpan]) {
        $Segment.Duration.TotalSeconds
    }
    else {
        ($endSeconds - $startSeconds)
    }

    $action = $Segment.Action

    #
    # Build structured comment block.
    #

    $startTs     = [TimeSpan]::FromSeconds($startSeconds).ToString('hh\:mm\:ss\.fff')
    $endTs       = [TimeSpan]::FromSeconds($endSeconds).ToString('hh\:mm\:ss\.fff')
    $durationFmt = $durationSeconds.ToString('0.###', $invariantCulture) + ' sec'

    $commentLines = [System.Collections.Generic.List[string]]::new()
    $commentLines.Add("Type           : Editing")
    $commentLines.Add("Decision       : $action")
    $commentLines.Add('')
    $commentLines.Add("Start          : $startTs")
    $commentLines.Add("End            : $endTs")
    $commentLines.Add("Duration       : $durationFmt")
    $commentLines.Add('')
    $commentLines.Add('Generated by PCXLab.VideoTools')

    $comments = $commentLines -join "`n"

    New-PCXPremiereMarkerObject `
        -StartSeconds  $startSeconds `
        -EndSeconds    $endSeconds `
        -Name          $action `
        -Comments      $comments `
        -MarkerKind    'Editing' `
        -MarkerSubKind $action

}
