function Convert-PCXAnalysisEventToPremiereMarker {

    <#
    .SYNOPSIS
        Converts an analysis event into a normalized Premiere marker object.

    .DESCRIPTION
        Transforms raw analysis events (such as PCXLab.Silence, PCXLab.BlackFrame,
        or any object conforming to Test-PCXAnalysisEvent) into a PCXLab.PremiereMarker.

        This function represents pure factual telemetry visualization with zero
        editing heuristics or policies applied.

        The resulting marker is always stamped with:
            MarkerKind    = 'Analysis'
            MarkerSubKind = the normalized EventType (e.g. 'Silence', 'BlackFrame')

        Marker title
        ------------
        A concise display name is used (e.g. 'Silence', 'Black Frame').
        Classification and duration are not included in the title.

        Marker comments
        ---------------
        A structured key-value block is generated:

            Type           : Analysis
            SubType        : Silence
            Classification : ShortPause     (only when available)

            Start          : 00:00:03.004
            End            : 00:00:04.430
            Duration       : 1.426 sec

            Generated by PCXLab.VideoTools

    .PARAMETER Event
        The analysis event object to convert.

    .OUTPUTS
        PCXLab.PremiereMarker
    #>

    [CmdletBinding()]
    [OutputType([PSCustomObject])]
    param(

        [Parameter(Mandatory)]
        [ValidateNotNull()]
        [object]$Event

    )

    $invariantCulture = [System.Globalization.CultureInfo]::InvariantCulture

    $startSeconds = if ($null -ne $Event.StartSeconds) {
        [double]$Event.StartSeconds
    }
    elseif ($Event.Start -is [TimeSpan]) {
        $Event.Start.TotalSeconds
    }
    else {
        0.0
    }

    $endSeconds = if ($null -ne $Event.EndSeconds) {
        [double]$Event.EndSeconds
    }
    elseif ($Event.End -is [TimeSpan]) {
        $Event.End.TotalSeconds
    }
    else {
        $startSeconds
    }

    $durationSeconds = if ($null -ne $Event.DurationSeconds) {
        [double]$Event.DurationSeconds
    }
    elseif ($Event.Duration -is [TimeSpan]) {
        $Event.Duration.TotalSeconds
    }
    else {
        ($endSeconds - $startSeconds)
    }

    #
    # Factual mapping based on EventType / PSTypeName.
    # MarkerKind is always 'Analysis' for all analysis events.
    # MarkerSubKind is derived from the domain type and drives color resolution.
    #

    if ($Event.PSTypeNames -contains 'PCXLab.Silence' -or $Event.EventType -eq 'Silence') {

        $markerSubKind       = 'Silence'
        $markerName          = 'Silence'
        $classificationValue = $Event.Classification

    }
    elseif ($Event.PSTypeNames -contains 'PCXLab.BlackFrame' -or $Event.EventType -eq 'BlackFrame') {

        $markerSubKind       = 'BlackFrame'
        $markerName          = 'Black Frame'
        $classificationValue = $null

    }
    else {

        $eventType = if (-not [string]::IsNullOrWhiteSpace($Event.EventType)) {
            $Event.EventType
        }
        else {
            'AnalysisEvent'
        }

        # Promote the EventType directly as the SubKind so future analysis types
        # (e.g. 'Speech', 'SceneChange') resolve their color without adapter changes.
        # Map known future EventTypes to their approved display names.
        $markerSubKind = $eventType
        $markerName    = switch ($eventType) {
            'Speech'       { 'Speech' }
            'SceneChange'  { 'Scene Change' }
            'Chapter'      { 'Chapter' }
            'AISuggestion' { 'AI Suggestion' }
            default        { $eventType }
        }
        $classificationValue = $null

    }

    #
    # Build structured comment block.
    #

    $startTs     = [TimeSpan]::FromSeconds($startSeconds).ToString('hh\:mm\:ss\.fff')
    $endTs       = [TimeSpan]::FromSeconds($endSeconds).ToString('hh\:mm\:ss\.fff')
    $durationFmt = $durationSeconds.ToString('0.###', $invariantCulture) + ' sec'

    $commentLines = [System.Collections.Generic.List[string]]::new()
    $commentLines.Add("Type           : Analysis")
    $commentLines.Add("SubType        : $markerSubKind")

    if (-not [string]::IsNullOrWhiteSpace($classificationValue)) {
        $commentLines.Add("Classification : $classificationValue")
    }

    $commentLines.Add('')
    $commentLines.Add("Start          : $startTs")
    $commentLines.Add("End            : $endTs")
    $commentLines.Add("Duration       : $durationFmt")
    $commentLines.Add('')
    $commentLines.Add('Generated by PCXLab.VideoTools')

    $comments = $commentLines -join "`n"

    New-PCXPremiereMarkerObject `
        -StartSeconds  $startSeconds `
        -EndSeconds    $endSeconds `
        -Name          $markerName `
        -Comments      $comments `
        -MarkerKind    'Analysis' `
        -MarkerSubKind $markerSubKind

}
